# Node Information
data-path="/mnt/data"
genesis-file="/mnt/config/genesis.json"
min-gas-price=0

# P2P network
p2p-enabled=true
discovery-enabled=false
p2p-host="0.0.0.0"
p2p-port="30301"

host-allowlist=["*"]

# JSON-RPC
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port="18453"
rpc-http-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]
rpc-http-cors-origins=["*"]
rpc-http-authentication-enabled=false

# WebSockets API
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port="18543"
rpc-ws-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET"]
rpc-ws-authentication-enabled=false
rpc-max-logs-range=0

# Metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port="19543"

# Logging
logging="DEBUG"
revert-reason-enabled=true

# Docker
nat-method="DOCKER"

# Key
node-private-key-file="/mnt/secrets/key"
